name: Docs (Maven)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - run: mvn -B -ntp clean verify
      - run: mvn -B -ntp javadoc:javadoc
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/docs/javadoc
          branch: gh-pages
